/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaoindicadores.views;


import gestaoindicadores.models.CRUD;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JRResultSetDataSource;

/**
 *
 * @author Usuario
 */
public class relatorioAcoesPorUsuarioFiltro extends javax.swing.JFrame {

    /**
     * Creates new form relatorioAcoesFiltro
     */
    public relatorioAcoesPorUsuarioFiltro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dataDe = new javax.swing.JFormattedTextField();
        dataAte = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro");

        jLabel1.setText("Data de:");

        jLabel2.setText("Data até:");

        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dataDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        dataAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(129, 129, 129))
                    .addComponent(dataDe)
                    .addComponent(dataAte))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(dataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(278, 254));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.dataDe.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DATA DE é obrigatório");
        }else if(this.dataAte.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DATA ATE é obrigatório");
        }else {
        
  
        String data_DE = this.dataDe.getText().toString();
                String dataEmUmFormato[] = data_DE.split("/");
                data_DE = dataEmUmFormato[2]+"-"+dataEmUmFormato[1]+"-"+dataEmUmFormato[0];
                
                
                
                String data_Ate = this.dataAte.getText().toString();
                dataEmUmFormato = data_Ate.split("/");
                data_Ate = dataEmUmFormato[2]+"-"+dataEmUmFormato[1]+"-"+dataEmUmFormato[0];
                
                
            // TODO add your handling code here:
           
        try {
            HashMap param = new HashMap();
            

            ResultSet result = new CRUD().select("SELECT " +
"status.descricao," +
"usuarios.nome," +
"acoes.oque," +
"acoes.quando," +
"acoes.idacoes" +
" FROM acoes" +
" INNER JOIN categorias ON acoes.categoria = categorias.idcategorias" +
" INNER JOIN usuarios ON acoes.quem = usuarios.idusuarios" +
" INNER JOIN status ON acoes.status = status.idstatus WHERE acoes.quando >= '"+data_DE+"' AND acoes.quando <= '"+data_Ate+"'");
            
            
            
            
            JRResultSetDataSource relatResult = new JRResultSetDataSource(result);
            
            JasperPrint jpPrint;
            jpPrint = JasperFillManager.fillReport("Relato\\relatorioAcoes.jasper", param,relatResult);
            
            JasperViewer jpViewer = new JasperViewer (jpPrint , false); //false - não encerra a aplicação ao fechar a janela
            
            jpViewer.setTitle("Relatório de ações");
            
            
            jpViewer.setVisible(true);
            
            jpViewer.toFront();
            
        } catch (JRException ex) {
            Logger.getLogger(relatorioAcoesPorUsuarioFiltro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relatorioAcoesPorUsuarioFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relatorioAcoesPorUsuarioFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relatorioAcoesPorUsuarioFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relatorioAcoesPorUsuarioFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new relatorioAcoesPorUsuarioFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dataAte;
    private javax.swing.JFormattedTextField dataDe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
